### PR TITLE
Trivial code correction to run mlp

### PR DESCRIPTION
**Pull request by SaumyaTiwari01**

### CODE REVIEW

**Comment by gndowns** [comment]
@SaumyaTiwari01  What's the purpose of this change?

**Comment by SaumyaTiwari01** [comment]
1. main.py does not run with ds=1 or 3 due to the following error: 
NameError: name 'geneparam' is not defined

2. In solving for this error (in the pull request) , other errors are raised: 
TypeError: unsupported operand type(s) for +: 'int' and 'list'

3. nb_neuron for each layer needs to be selected from list of nb_neurons, therefore the following code should have nb_neurons[i] instead of nb_neurons:

```
for i in range(nb_layers):

        # Need input shape for first layer.
        if i == 0:
            model.add(Dense(nb_neurons, activation=activation, input_shape=input_shape))
        else:
            model.add(Dense(nb_neurons, activation=activation))
```

**Comment by jliphard** [comment]
> @SaumyaTiwari01 What's the purpose of this change?

@gndowns I'm traveling and will not have time to dig into this for a day or two - does this change make sense? If so I will merge. Thanks!

**Comment by gndowns** [comment]
@jliphard Looks good to me! I must've forgotten to update these when I changed `nb_neurons` to a list.

**Comment by jliphard** [comment]
thank you @SaumyaTiwari01

**Comment by SaumyaTiwari01** [comment]
No problem!

**Pull request merged**
